[package]
name = "IROOJ_Frontend"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.10" #rocket webframework
urlencoding = "2.1.0" #url encode/decode
